export { default as NavBar } from "./NavBar";
export { default as Chat } from "./Chat";
export { default as LeaderBoardTable } from "./LeaderBoardTable";
export { default as Settings } from "./Settings";
export { default as Footer } from "./Footer";
export { default as PlayersBoard } from "./PlayersBoard";
export { default as Countdown } from "./Countdown";
export { default as Canvas } from "./Canvas";
export { default as Word } from "./Word";
export { default as CorrectPlayer } from "./CorrectPlayer"
